name: Build documentation

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 3 * * *' # nightly job at 3am UTC

jobs:
  build:
    runs-on: windows-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build docs
        shell: powershell
        run: |
          cd $env:GITHUB_WORKSPACE/parts
          python -m pip install pydoc-markdown
          pydoc-markdown
          $file = get-content emio-sofa-api.md
          $file | ForEach-Object {if ($_.ReadCount -eq 1) {$_ -replace "^.*", "# Emio SOFA API"} else {$_}} | Set-Content .\emio-sofa-api.md
          cd $env:GITHUB_WORKSPACE

      - name: Set env vars and rename executables
        shell: powershell
        run: |
          $PROJECT_NAME = $env:GITHUB_REPOSITORY.Split('/')[1]
          Add-Content -Path $env:GITHUB_ENV -Value "PROJECT_NAME=$PROJECT_NAME"
          
          $RELEASE_NAME = $env:GITHUB_REF_NAME.Split('/')[
          $RELEASE_TAGNAME = "release-$RELEASE_NAME"
          $BRANCH_NAME = $RELEASE_NAME
          $RELEASE_DATE = (Get-Date -Format "yyyy-MM-dd (at HH:mm:ss UTC)")
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_NAME=$RELEASE_NAME"
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_TAGNAME=$RELEASE_TAGNAME"
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_DATE=$RELEASE_DATE"

      - name: Delete old release
        if: success() || failure()
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          tag_name: ${{ env.RELEASE_TAGNAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
          
      - name: Create Release
        if: success() || failure()
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_TAGNAME }}
          fail_on_unmatched_files: false
          target_commitish: ${{ github.sha }}
          draft: false
          files: |
            parts/emio-sofa-api.md
